### ISSUE TITLE
Border color of the .ui-btn-up-('e' and 'f') theme

### ISSUE THREAD

**Issue by alyc** [commadelimited/jQuery-Mobile-Bootstrap-Theme#5]
Hi,

Great work here :) 

Just want to let you know that the border color of the .ui-btn-up-e and .ui-btn-up-f is #cccccc, which seems strange while the other themes are theme looks nicer with the darker border of their respective color.

I just replace with
border: 1px solid   #009bb7
and 
border: 1px solid   #f28f00

for .ui-btn-up-e and .ui-btn-up-f respectively, which looks much better without the #cccccc border.

Kind Regards
Andy

**Comment by commadelimited** [comment]
Hey @alyc, would you be interested in submitting a pull request to fix that color issue? I'd be happy to pull it in.

**Comment by commadelimited** [comment]
Closed via https://github.com/commadelimited/jQuery-Mobile-Bootstrap-Theme/commit/a58f53734180a078ad8ca484e926feb31ccd5eba
