### ISSUE TITLE
black box in checkbox checked state

### ISSUE THREAD

**Issue by ravimallya** [commadelimited/jQuery-Mobile-Bootstrap-Theme#7]
I'm a bootstrap lover and first of all let me thank you for your efforts. I found an issue in checkbox while it in checked state as shown in the screenshot. A small black box appears under the check arrow.

![image](https://f.cloud.github.com/assets/2795843/443398/1e5f444e-b17d-11e2-9bda-52326ca22588.png)

I used latest version of Google chrome in Windows 7 Desktop.
Can you please look into this? Thanks

**Comment by commadelimited** [comment]
@ravimallya I just reviewed the demo on my website: http://andymatthews.net/code/jQuery-Mobile-Bootstrap-Theme/

I was able to confirm the black square indicated in your screenshot. It appears however that my website hadn't been updated with the code from this repository. I've uploaded that code and now the black square is gone using Chrome for Mac: **Version 28.0.1500.6 dev**

Can you confirm?

**Comment by ravimallya** [comment]
Hi. The issue still persists. in your demo website itself. I've not tried to integrate it with custom html, because of no time. You may check the screenshot.

![untitled](https://f.cloud.github.com/assets/2795843/521241/6dd4ed64-bf8b-11e2-9696-61ec7e8c12e7.jpg)

I checked in latest version of Chrome, Firefox and IE10 in Windows 8. Thank you for taking care of this.

**Comment by patik** [comment]
I still see it on iOS 6 as well:

![image](https://f.cloud.github.com/assets/262137/521456/e3f95b72-bfa6-11e2-8c17-f8145edade91.jpg)

**Comment by commadelimited** [comment]
This should be resolved now.

**Comment by ravimallya** [comment]
Yes, Now it's fine. thank you.
