### ISSUE TITLE
text-shadow has undefined value

### ISSUE THREAD

**Issue by surenrao** [commadelimited/jQuery-Mobile-Bootstrap-Theme#8]
I would recommend to use text-shadow:none
text-shadow: undefined /_{a-bup-shadow-x}_/ undefined /_{a-bup-shadow-y}_/ undefined /_{a-bup-shadow-radius}_/ undefined /_{a-bup-shadow-color}_/;

text-shadow: 0 /_{a-body-shadow-x}_/ 0 /_{a-body-shadow-y}_/ 0 /_{a-body-shadow-radius}_/ #000000 /_{a-body-shadow-color}_/;

**Comment by commadelimited** [comment]
@surenrao would you care to open a pull request to fix the bug?
